Repository Finance-uss/Finance_Us_FE, pull requests merged in 2025-01, with the labels that each got.

#1 feat: ci 파이프라인 구축
  .github/workflows/ci.yml
Labels: :sparkles: FEAT

#3 feat: 페이지 라우팅 설정
  index.html
  src/App.jsx
  src/pages/Alarm/index.jsx
  src/pages/Community/index.jsx
  src/pages/Finance/index.jsx
  src/pages/FindId/index.jsx
  src/pages/FindPW/index.jsx
  src/pages/Login/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/Onboarding/index.jsx
  src/pages/ProfileSetting/index.jsx
  src/pages/SignUp/index.jsx
  src/pages/Statistics/index.jsx
  src/pages/User/index.jsx
Labels: :sparkles: FEAT

#6 feat: CateButton, PlusButton, TopBar 제작 및 User 페이지에 구현
  src/App.jsx
  src/assets/icons/common/Hide-Indicator.svg
  src/assets/icons/common/Vector.svg
  src/components/common/CateButton/index.jsx
  src/components/common/PlusButton/index.jsx
  src/components/common/TopBar/index.jsx
  src/index.css
  src/pages/User/index.jsx
  src/styles/common/CateButton/style.js
  src/styles/common/PlusButton/style.js
  src/styles/common/TopBar/style.js
Labels: :sparkles: FEAT

#7 Feature/common3
  src/App.jsx
  src/components/common/FinanceButton/index.jsx
  src/components/common/SubmitButton/index.jsx
  src/pages/Login/index.jsx
  src/styles/common/FinanceButton/style.js
  src/styles/common/SubmitButton/style.js
Labels: :sparkles: FEAT

#12 feat: finance 페이지 및 캘린더 컴포넌트 구현
  src/assets/icons/common/Bell.svg
  src/assets/icons/common/BellAlert.svg
  src/components/Finance/Calendar/index.jsx
  src/pages/Finance/index.jsx
  src/styles/Finance/Calendar/style.js
  src/styles/Finance/style.js
  src/styles/common/NavBar/YearMonthModal/style.js
Labels: :sparkles: FEAT

#13 feat: 커뮤니티 게시글 페이지, 게시글 작성 페이지, 알림 페이지
  src/App.jsx
  src/assets/icons/common/Alarm.svg
  src/assets/icons/common/Before.svg
  src/assets/icons/common/Community/Checked.svg
  src/assets/icons/common/Community/comment.svg
  src/assets/icons/common/Community/exam.png
  src/assets/icons/common/Community/heart.svg
  src/assets/icons/common/Search.svg
  src/components/Alarm/AlarmCard/index.jsx
  src/components/Alarm/AlarmList/inedx.jsx
  src/components/Community/Board/PostCard/index.jsx
  src/components/Community/Board/PostList/index.jsx
  src/components/Community/Category/CateButton/index.jsx
  src/components/Community/Category/CateSelect/index.jsx
  src/components/Community/Profile/index.jsx
  src/components/Community/SearchBar/index.jsx
  src/components/common/BeforeHeader/index.jsx
  src/components/common/BottomBar/index.jsx
  src/components/common/FloatingButton/CommunityWriteButton/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/components/common/TopBar/index.jsx
  src/index.css
  src/layouts/layout.jsx
  src/pages/Alarm/index.jsx
  src/pages/Community/CommunityMain/index.jsx
  src/pages/Community/PostWrite/index.jsx
  src/pages/Community/index.jsx
  src/pages/Search/index.jsx
  src/styles/Alarm/style.js
  src/styles/Community/Category/CateButton/style.js
  src/styles/Community/Category/CateSelect/style.js
  src/styles/Community/PostCard/style.js
  src/styles/Community/PostWrite/style.js
  src/styles/Community/Profile/style.js
  src/styles/common/BeforeHeader/style.js
  src/styles/common/BottomBar/style.js
Labels: :sparkles: FEAT

#15 feat: 가계부_수기작성 페이지 구현 및 중첩 라우팅 구현
  src/App.jsx
  src/assets/icons/finance/Line.svg
  src/components/common/FinanceButton/index.jsx
  src/hooks/useModal.js
  src/pages/Finance/FinanceMain/index.jsx
  src/pages/Finance/HandWrite/AssetModal/index.jsx
  src/pages/Finance/HandWrite/CategoryModal/index.jsx
  src/pages/Finance/HandWrite/RatingModal/index.jsx
  src/pages/Finance/HandWrite/index.jsx
  src/pages/Finance/index.jsx
  src/styles/Finance/FinanceMain/style.js
  src/styles/Finance/HandWrite/style.js
Labels: :sparkles: FEAT

#18 feat: 가계부 메인 페이지 구현
  src/assets/icons/finance/CaretRight.svg
  src/components/Finance/Satisfaction/index.jsx
  src/components/common/FloatingButton/FinancePlusButton/index.jsx
  src/pages/Finance/FinanceMain/index.jsx
  src/styles/Finance/Satisfaction/style.js
  src/styles/common/NavBar/style.js
Labels: :sparkles: FEAT

#21 feat: 가계부 레포트 페이지 구현, normalize css 적용, financeContext파일 구현
  package-lock.json
  package.json
  src/App.jsx
  src/contexts/financeContext.jsx
  src/pages/Finance/Report/index.jsx
  src/pages/Finance/index.jsx
  src/styles/Finance/Report/style.js
  src/styles/common/BeforeHeader/style.js
Labels: :sparkles: FEAT

#25 Feature/signup
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/common/Logo.svg
  src/assets/icons/common/Subtitle.svg
  src/components/Dropdown/index.jsx
  src/components/common/SubmitButton/index.jsx
  src/pages/FindId/index.jsx
  src/pages/FindMail/index.jsx
  src/pages/FindPW/index.jsx
  src/pages/Login/index.jsx
  src/pages/NewPW/index.jsx
  src/pages/Onboarding/index.jsx
  src/pages/ProfileSetting/index.jsx
  src/pages/SetPW/index.jsx
  src/pages/SignUp/index.jsx
  src/pages/Statistics/index.jsx
  src/styles/Dropdown/style.js
  src/styles/FindMail/style.js
  src/styles/FindPW/style.js
  src/styles/Login/style.js
  src/styles/NewPW/style.js
  src/styles/ProfileSetting/style.js
  src/styles/SetPW/style.js
  src/styles/SignUp/style.js
  src/styles/common/SubmitButton/style.js
Labels: :sparkles: FEAT

#28 feat: 마이페이지 카테고리 설정 페이지 구현 및 TopBar 컴포넌트 수정
  src/App.jsx
  src/assets/icons/common/CaretLeft.svg
  src/assets/icons/common/User/DeleteCate.svg
  src/assets/icons/common/User/PlusCate.svg
  src/assets/icons/common/User/PostImage1.svg
  src/assets/icons/common/User/PostImage2.svg
  src/assets/icons/common/User/PostImage3.svg
  src/assets/icons/common/User/PostImage4.svg
  src/assets/icons/common/User/Scrapped.svg
  src/components/User/AmountInput/index.jsx
  src/components/User/AmountInputContainer/index.jsx
  src/components/User/BackHeader/index.jsx
  src/components/User/CateContainer/index.jsx
  src/components/User/CompleteButton/index.jsx
  src/components/User/PlusCateButton/index.jsx
  src/components/User/UserPostCard/index.jsx
  src/components/common/TopBar/index.jsx
  src/pages/User/Setting/Assets/index.jsx
  src/pages/User/Setting/Category/index.jsx
  src/pages/User/Setting/CategoryExpense/index.jsx
  src/pages/User/Setting/CategoryIncome/index.jsx
  src/pages/User/Setting/Commented/index.jsx
  src/pages/User/Setting/Expense/index.jsx
  src/pages/User/Setting/Income/index.jsx
  src/pages/User/Setting/Liked/index.jsx
  src/pages/User/Setting/My/index.jsx
  src/pages/User/Setting/Scrapped/index.jsx
  src/pages/User/UserMain/index.jsx
  src/styles/User/AmountInput/style.js
  src/styles/User/AmountInputContainer/style.js
  src/styles/User/BackHeader/style.js
  src/styles/User/CateContainer/style.js
  src/styles/User/CompleteButton/style.js
  src/styles/User/PlusCateButton/style.js
  src/styles/User/UserPostCard/style.js
Labels: :sparkles: FEAT

#29 feat: 친구 가계부 페이지 및 검색 페이지 구현
  src/App.jsx
  src/assets/icons/common/Bookmark.svg
  src/assets/icons/common/Community/CommentSubmit.svg
  src/assets/icons/common/Community/SearchPrimaryColor.svg
  src/assets/icons/common/Community/defaultProfile.svg
  src/assets/icons/common/Community/delete.svg
  src/assets/icons/common/Community/more.svg
  src/components/Community/Board/PostList/index.jsx
  src/components/Community/Category/CateButton/index.jsx
  src/components/Community/Category/CateSelect/index.jsx
  src/components/Community/FollowFinance/Budget/index.jsx
  src/components/Community/FollowFinance/FinanceCard/index.jsx
  src/components/Community/Profile/index.jsx
  src/components/Community/Search/Preview/index.jsx
  src/components/Community/Search/RecentSearch/index.jsx
  src/components/Community/Search/SearchProfile/index.jsx
  src/components/Community/SearchBar/index.jsx
  src/components/common/BeforeHeader/index.jsx
  src/components/common/FloatingButton/FinancePlusButton/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/components/common/TopBar/index.jsx
  src/pages/Alarm/index.jsx
  src/pages/Community/CommunityMain/index.jsx
  src/pages/Community/FollowFinance/index.jsx
  src/pages/Community/PostDetail/index.jsx
  src/pages/Community/PostWrite/index.jsx
  src/pages/Search/SearchResult/index.jsx
  src/pages/Search/index.jsx
  src/styles/Alarm/style.js
  src/styles/Community/Category/CateButton/style.js
  src/styles/Community/Category/CateSelect/style.js
  src/styles/Community/CommunityMain/style.js
  src/styles/Community/FollowFinance/Budget/style.js
  src/styles/Community/FollowFinance/FinanceCard/style.js
  src/styles/Community/FollowFinance/style.js
  src/styles/Community/PostDetail/Comment/style.js
  src/styles/Community/PostDetail/Content/style.js
  src/styles/Community/PostWrite/style.js
  src/styles/Community/RecentSearch/style.js
  src/styles/Community/Search/style.js
  src/styles/Community/SearchBar/style.js
  src/styles/Community/SearchPreview/style.js
  src/styles/Community/SearchProfile/style.js
  src/styles/common/BeforeHeader/style.js
  src/styles/common/FloatingButton/FinancePlusButton/style.js
Labels: :sparkles: FEAT

#31 Feature/finance handwrite
  src/assets/icons/finance/AddPhotoAlternate.svg
  src/components/Finance/Calendar/CalendarGrid/DayCell/index.jsx
  src/components/Finance/Calendar/CalendarGrid/index.jsx
  src/components/Finance/Calendar/Header/index.jsx
  src/components/Finance/Calendar/index.jsx
  src/components/Finance/HandWrite/AssetModal/index.jsx
  src/components/Finance/HandWrite/CalendarModal/index.jsx
  src/components/Finance/HandWrite/CategoryModal/index.jsx
  src/components/Finance/HandWrite/InputField/index.jsx
  src/components/Finance/HandWrite/OtherSection/index.jsx
  src/components/Finance/HandWrite/RatingModal/index.jsx
  src/components/Finance/HandWrite/TextSection/index.jsx
  src/components/Finance/Satisfaction/index.jsx
  src/components/common/NavBar/AlarmIcon/index.jsx
  src/components/common/NavBar/DateSelector/YearMonthModal/MonthSelector/index.jsx
  src/components/common/NavBar/DateSelector/YearMonthModal/YearSelector/index.jsx
  src/components/common/NavBar/DateSelector/YearMonthModal/index.jsx
  src/components/common/NavBar/DateSelector/index.jsx
  src/components/common/NavBar/YearMonthModal/MonthSelector/index.jsx
  src/components/common/NavBar/YearMonthModal/YearSelector/index.jsx
  src/components/common/NavBar/YearMonthModal/index.jsx
  src/components/common/NavBar/index.jsx
  src/contexts/DateContext.jsx
  src/contexts/HandWriteContext.jsx
  src/contexts/financeContext.jsx
  src/hooks/useCalendar.js
  src/hooks/useForm.js
  src/hooks/useImageUploader.js
  src/hooks/useModal.js
  src/hooks/useModalManager.js
  src/hooks/useScrollSelector.js
  src/pages/Finance/FinanceMain/index.jsx
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/pages/Finance/HandWrite/RatingModal/index.jsx
  src/pages/Finance/HandWrite/index.jsx
  src/pages/Finance/Report/index.jsx
  src/pages/Finance/index.jsx
  src/styles/Finance/Calendar/style.js
  src/styles/Finance/FinanceMain/style.js
  src/styles/Finance/HandWrite/style.js
  src/styles/Finance/Satisfaction/style.js
  src/styles/Finance/style.js
  src/styles/common/NavBar/AlarmIcon/style.js
  src/styles/common/NavBar/DateSelector/YearMonthModal/MonthSelector/style.js
  src/styles/common/NavBar/DateSelector/YearMonthModal/YearSelector/style.js
  src/styles/common/NavBar/DateSelector/YearMonthModal/style.js
  src/styles/common/NavBar/DateSelector/style.js
  src/styles/common/NavBar/style.js
Labels: :sparkles: FEAT, :recycle: REFACTOR

#32 feat: 게시글 상세 페이지 구현 및 컴포넌트 스타일 수정
  src/App.jsx
  src/assets/icons/common/Bookmark.svg
  src/assets/icons/common/Community/commentProfile.svg
  src/assets/icons/common/Community/commentSubmit.svg
  src/assets/icons/common/Community/heart.svg
  src/assets/icons/common/Community/heartFill.svg
  src/assets/icons/common/Community/more.svg
  src/assets/icons/common/bookmark.svg
  src/components/Community/Board/PostCard/index.jsx
  src/components/Community/Board/PostList/index.jsx
  src/components/Community/Category/CateButton/index.jsx
  src/components/Community/FollowFinance/Budget/index.jsx
  src/components/Community/Post/Comment/CommentInput/index.jsx
  src/components/Community/Post/Comment/CommentList/Comment/index.jsx
  src/components/Community/Post/Comment/CommentList/Reply/index.jsx
  src/components/Community/Post/Comment/CommentList/index.jsx
  src/components/Community/Post/Content/index.jsx
  src/components/Community/Post/CustomDate/index.jsx
  src/components/Community/Post/MenuBar/index.jsx
  src/pages/Alarm/index.jsx
  src/pages/Community/FollowFinance/index.jsx
  src/pages/Community/PostDetail/index.jsx
  src/pages/Community/PostWrite/index.jsx
  src/pages/Search/SearchResult/index.jsx
  src/pages/Search/index.jsx
  src/styles/Alarm/style.js
  src/styles/Community/CommunityMain/style.js
  src/styles/Community/FollowFinance/Budget/style.js
  src/styles/Community/FollowFinance/style.js
  src/styles/Community/MenuBar/style.js
  src/styles/Community/PostCard/style.js
  src/styles/Community/PostDetail/Comment/style.js
  src/styles/Community/PostDetail/CommentInput/style.js
  src/styles/Community/PostDetail/Content/style.js
  src/styles/Community/PostWrite/style.js
  src/styles/Community/Search/style.js
  src/styles/common/BeforeHeader/style.js
  src/styles/common/BottomBar/style.js
Labels: :sparkles: FEAT

#34 feat: 마이페이지 스타일 전체 수정
  src/components/User/ColorPick/index.jsx
  src/components/User/Highlight/index.jsx
  src/components/common/TopBar/index.jsx
  src/pages/User/Setting/CategoryExpense/index.jsx
  src/pages/User/Setting/CategoryIncome/index.jsx
  src/pages/User/Setting/Expense/index.jsx
  src/pages/User/Setting/Income/index.jsx
  src/pages/User/UserMain/index.jsx
  src/styles/User/AmountInput/style.js
  src/styles/User/AmountInputContainer/style.js
  src/styles/User/BackHeader/style.js
  src/styles/User/CateContainer/style.js
  src/styles/User/ColorPick/style.js
  src/styles/User/CompleteButton/style.js
  src/styles/User/Highlight/style.js
  src/styles/User/PlusCateButton/style.js
  src/styles/User/SettingOption/style.js
  src/styles/common/CateButton/style.js
  src/styles/common/PlusButton/style.js
  src/styles/common/TopBar/style.js
Labels: :recycle: REFACTOR

#38 feat: 로그인 기능 구현
  src/components/common/FinanceButton/index.jsx
  src/pages/Login/index.jsx
Labels: :sparkles: FEAT

#40 feat: 회원가입 기능 구현
  src/App.jsx
  src/api/axiosInstance.js
  src/contexts/AuthContext.jsx
  src/pages/FindPW/index.jsx
  src/pages/NewPW/index.jsx
  src/pages/ProfileSetting/index.jsx
  src/pages/SetPW/index.jsx
  src/pages/SignUp/index.jsx
Labels: :sparkles: FEAT
