Repository Finance-uss/Finance_Us_FE, pull requests merged in 2025-02, with the labels that each got.

#46 마이페이지 개인 정보 변경, 캘린더, 계정 정보 페이지 구현 및 스타일 수정
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/common/User/ChangeProfile.svg
  src/components/User/ChangeProfile/index.jsx
  src/components/User/ColorPick/index.jsx
  src/components/User/ConfirmModal/index.jsx
  src/components/User/Highlight/index.jsx
  src/components/User/InputWithButton/index.jsx
  src/components/User/ProfileForm/index.jsx
  src/components/User/SettingPanel/index.jsx
  src/components/User/SimpleInput/index.jsx
  src/components/User/UserPostCard/index.jsx
  src/pages/User/Panel/Calendar/index.jsx
  src/pages/User/Panel/Email/index.jsx
  src/pages/User/Panel/Password/index.jsx
  src/pages/User/Panel/Profile/index.jsx
  src/pages/User/Setting/CategoryExpense/index.jsx
  src/pages/User/Setting/CategoryIncome/index.jsx
  src/pages/User/Setting/Commented/index.jsx
  src/pages/User/Setting/Expense/index.jsx
  src/pages/User/Setting/Income/index.jsx
  src/pages/User/Setting/Liked/index.jsx
  src/pages/User/Setting/My/index.jsx
  src/pages/User/Setting/Scrapped/index.jsx
  src/pages/User/UserMain/index.jsx
  src/styles/User/BackHeader/style.js
  src/styles/User/ChangeProfile/style.js
  src/styles/User/ColorPick/style.js
  src/styles/User/ConfirmModal/style.js
  src/styles/User/Highlight/style.js
  src/styles/User/InputWithButton/style.js
  src/styles/User/ProfileForm/style.js
  src/styles/User/SettingOption/style.js
  src/styles/User/SettingPanel/style.js
  src/styles/User/SimpleInput/style.js
  src/styles/User/UserPostCard/style.js
  src/styles/User/UserProfile/style.js
Labels: :sparkles: FEAT, :recycle: REFACTOR

#51 feat: 가계부 수기작성 api연결
  src/api/account.js
  src/hooks/useAccount.js
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/utils/accountUtils.js
Labels: :sparkles: FEAT

#54 fix: react-swipeable 라이브러리 설치
  package-lock.json
Labels: :bug: FIX

#45 feat: 알림 API 연결
  package-lock.json
  package.json
  src/api/apiComment.js
  src/assets/icons/common/Community/CheckCircle.svg
  src/components/Alarm/AlarmCard/index.jsx
  src/components/Alarm/AlarmList/index.jsx
  src/components/Community/Post/Comment/CommentList/Comment/index.jsx
  src/components/Community/Post/Comment/CommentList/Reply/index.jsx
  src/components/Community/Post/Comment/CommentList/index.jsx
  src/components/Community/Post/Content/index.jsx
  src/components/Community/Post/MenuBar/CommentMenubar/index.jsx
  src/components/Community/Post/MenuBar/PostMenubar/index.jsx
  src/components/Community/Post/MenuBar/index.jsx
  src/components/Community/Search/Preview/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/hooks/useComment.js
  src/main.jsx
  src/pages/Alarm/index.jsx
  src/pages/Community/PostDetail/index.jsx
  src/pages/Community/PostWrite/index.jsx
  src/pages/Search/SearchResult/index.jsx
  src/styles/Community/Category/CateButton/style.js
  src/styles/Community/CommunityMain/style.js
  src/styles/Community/MenuBar/style.js
  src/styles/Community/PostDetail/CommentInput/style.js
  src/styles/Community/PostDetail/Content/style.js
  src/styles/Community/PostWrite/style.js
  src/styles/Community/Profile/style.js
  src/styles/Community/RecentSearch/style.js
  src/styles/Community/SearchBar/style.js
  src/styles/common/SearchHeader/style.js
  src/utils/dateUtils.js
Labels: :sparkles: FEAT

#50 style: 가계부 플로팅 버튼 스타일 수정
  index.html
  public/FinanceUs_Icon.svg
  src/components/common/FloatingButton/FinancePlusButton/index.jsx
  src/styles/common/FloatingButton/CommunityWriteButton/style.js
  src/styles/common/FloatingButton/FinancePlusButton/style.js
Labels: 🎨 STYLE

#56 로그인 회원가입 API 연결 (이메일 및 비밀번호 재설정)
  src/assets/icons/common/Community/CommentSubmit.svg
  src/assets/icons/common/drop.svg
  src/components/Dropdown/index.jsx
  src/components/PW/index.jsx
  src/contexts/AuthContext.jsx
  src/pages/FindMail/index.jsx
  src/pages/FindPW/index.jsx
  src/pages/Login/index.jsx
  src/pages/NewPW/index.jsx
  src/pages/Onboarding/index.jsx
  src/pages/ProfileSetting/index.jsx
  src/pages/SetPW/index.jsx
  src/pages/SignUp/index.jsx
  src/styles/FindMail/style.js
  src/styles/FindPW/style.js
  src/styles/Login/style.js
  src/styles/NewPW/style.js
  src/styles/ProfileSetting/style.js
  src/styles/SetPW/style.js
  src/styles/SignUp/style.js
Labels: :sparkles: FEAT

#58 [FEAT] 가계부 페이지 API 연결
  src/App.jsx
  src/components/Finance/Account/Activity/Item/index.jsx
  src/components/Finance/Account/List/Item/index.jsx
  src/components/Finance/Account/List/index.jsx
  src/components/Finance/Account/SwipeableCard/index.jsx
  src/components/Finance/HandWrite/AssetModal/index.jsx
  src/components/Finance/HandWrite/CalendarModal/index.jsx
  src/components/Finance/HandWrite/CategoryModal/index.jsx
  src/components/Finance/HandWrite/RatingModal/index.jsx
  src/components/Finance/Satisfaction/index.jsx
  src/contexts/DateContext.jsx
  src/contexts/HandWriteContext.jsx
  src/hooks/useApi.js
  src/hooks/useSwipe.js
  src/pages/Finance/AccountDetail/index.jsx
  src/pages/Finance/FinanceMain/index.jsx
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/pages/Finance/Report/index.jsx
  src/styles/Finance/Account/Activity/style.js
  src/styles/Finance/Calendar/style.js
  src/styles/Finance/HandWrite/style.js
  src/styles/Finance/style.js
  src/utils/accountUtils.js
Labels: :sparkles: FEAT

#65 chore: navbar가 wheel이벤트 이외에 다른 이벤트도 지원하도록 수정
  src/hooks/useScrollSelector.js
Labels: :clipboard: CHORE

#62 refactor: 알림 API 연결 수정
  src/components/Alarm/AlarmCard/index.jsx
  src/components/Alarm/AlarmList/index.jsx
  src/components/common/SearchHeader/Alarm/index.jsx
  src/components/common/SearchHeader/Search/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/pages/Alarm/index.jsx
  src/styles/common/SearchHeader/style.js
Labels: :recycle: REFACTOR

#61 feat: 팔로우 API 연결
  src/App.jsx
  src/api/apiFollow.js
  src/assets/icons/common/Community/followfinance.svg
  src/components/Community/FollowFinance/FinanceCard/index.jsx
  src/components/Community/Profile/index.jsx
  src/components/Community/Search/SearchProfile/index.jsx
  src/pages/Community/CommunityMain/index.jsx
  src/pages/Community/FollowFinance/index.jsx
  src/styles/Community/CommunityMain/style.js
  src/styles/Community/Profile/style.js
Labels: :sparkles: FEAT

#71 refactor: 알림 읽음 처리 수정
  src/components/Alarm/AlarmCard/index.jsx
  src/pages/Alarm/index.jsx
Labels: :sparkles: FEAT

#57 feat: 게시글 생성, 수정, 삭제, 스크랩 API 연결
  src/App.jsx
  src/api/post.js
  src/assets/icons/common/Community/Scrap.svg
  src/components/Community/Category/CateSelect/index.jsx
  src/components/Community/Post/Comment/CommentList/index.jsx
  src/components/Community/Post/Content/index.jsx
  src/components/Community/Post/MenuBar/PostMenubar/index.jsx
  src/hooks/useComment.js
  src/pages/Community/PostDetail/index.jsx
  src/pages/Community/PostWrite/index.jsx
Labels: :sparkles: FEAT

#70 feat: 특정 게시글 및 카테고리 목록 조회 api 연결
  src/api/apiPost.js
  src/components/Community/Board/PostCard/index.jsx
  src/components/Community/Board/PostList/index.jsx
  src/components/Community/Category/CateButton/index.jsx
  src/pages/Community/CommunityMain/index.jsx
  src/styles/Community/PostCard/style.js
Labels: :sparkles: FEAT

#73 feat: S3 post + S3 delete 기능 추가
  src/api/financeAPI.js
  src/api/s3API.js
  src/components/Finance/Account/Activity/Item/index.jsx
  src/components/Finance/Account/List/Item/index.jsx
  src/components/Finance/Account/SwipeableCard/index.jsx
  src/components/Finance/AccountDetail/OtherSection/index.jsx
  src/components/Finance/HandWrite/OtherSection/index.jsx
  src/components/common/NavBar/index.jsx
  src/contexts/HandWriteContext.jsx
  src/hooks/useApi.js
  src/hooks/useImageUploader.js
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/utils/accountUtils.js
Labels: :sparkles: FEAT

#75 Feature/statistics
  src/api/periodStatistics.js
  src/api/statistics.js
  src/components/Chart/BarChart/index.jsx
  src/components/Chart/DonutChart/index.jsx
  src/components/Stat/Category.jsx
  src/components/common/NavBar1/AlarmIcon/index.jsx
  src/components/common/NavBar1/DateSelector/YearMonthModal/MonthSelector/index.jsx
  src/components/common/NavBar1/DateSelector/YearMonthModal/YearSelector/index.jsx
  src/components/common/NavBar1/DateSelector/YearMonthModal/index.jsx
  src/components/common/NavBar1/DateSelector/index.jsx
  src/components/common/NavBar1/index.jsx
  src/components/common/NavBar2/DateRangeSelector/YearMonthRangeModal/index.jsx
  src/components/common/NavBar2/DateRangeSelector/index.jsx
  src/components/common/NavBar2/index.jsx
  src/pages/Statistics/StatMain/index.jsx
  src/styles/Chart/BarChart/style.js
  src/styles/Chart/DonutChart/style.js
  src/styles/Statistics/style.js
  src/styles/common/NavBar2/DateRangeSelector/YearMonthRangeModal/style.js
Labels: :sparkles: FEAT

#82 Refactor/ 게시글, 마이페이지 이미지 관련 기능
  src/api/userImageAPI.js
  src/components/Community/Post/Comment/CommentInput/index.jsx
  src/components/User/ChangeProfile/index.jsx
  src/components/User/UserProfile/ProfileImageUploader/index.jsx
  src/components/User/UserProfile/index.jsx
  src/pages/Community/PostWrite/index.jsx
  src/pages/User/Panel/Profile/index.jsx
  src/pages/User/Setting/Auth/index.jsx
  src/styles/Community/PostWrite/style.js
  src/styles/User/UserProfile/style.js
  src/utils/uploadImage.js
Labels: :recycle: REFACTOR

#86 refactor: 인증 여부에 따른 카테고리 선택 로직 수정
  src/components/Community/Category/CateSelect/index.jsx
  src/pages/Community/PostWrite/index.jsx
Labels: :recycle: REFACTOR

#85 feat: 검색 API 연결
  src/api/followAPI.js
  src/components/Community/FollowFinance/FinanceCard/index.jsx
  src/components/Community/Search/Preview/index.jsx
  src/components/Community/Search/SearchProfile/index.jsx
  src/pages/Community/CommunityMain/index.jsx
  src/pages/Community/FollowFinance/index.jsx
  src/pages/Search/SearchResult/index.jsx
Labels: :sparkles: FEAT

#94 style: navbar가 fixed유무를 인자로 받을 수 있도록 수정
  src/components/common/NavBar/DateSelector/YearMonthModal/index.jsx
  src/components/common/NavBar/DateSelector/index.jsx
  src/components/common/NavBar/index.jsx
  src/pages/Finance/FinanceMain/index.jsx
  src/pages/Finance/Report/index.jsx
  src/styles/common/NavBar/DateSelector/YearMonthModal/style.js
  src/styles/common/NavBar/style.js
Labels: 🎨 STYLE

#90 feat: 카메라 기능 구현 및 달력 하이라이트 구현
  src/App.jsx
  src/assets/icons/finance/Shutter.svg
  src/components/Finance/Calendar/CalendarGrid/DayCell/index.jsx
  src/components/Finance/Calendar/CalendarGrid/index.jsx
  src/components/Finance/Calendar/index.jsx
  src/components/Finance/HandWrite/OtherSection/index.jsx
  src/components/common/FloatingButton/FinancePlusButton/index.jsx
  src/contexts/HandWriteContext.jsx
  src/pages/Finance/Camera/index.jsx
  src/pages/Finance/FinanceMain/index.jsx
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/styles/Finance/Calendar/style.js
  src/styles/Finance/Camera/style.js
Labels: :sparkles: FEAT

#97 feat: searchHeader 높이 수정 & 인증 뱃지 위치 수정
  src/pages/User/UserMain/index.jsx
  src/styles/User/UserProfile/style.js
Labels: 💄 DESIGN

#101 fix: 상세 페이지 이동 시 이미지 사라지는 문제 해결 + 카메라 페이지 스타일링 수정
  src/components/Finance/AccountDetail/OtherSection/index.jsx
  src/contexts/AccountDetailContext.jsx
  src/pages/Finance/Camera/index.jsx
  src/styles/Finance/Camera/style.js
Labels: :bug: FIX, 🎨 STYLE

#98 fix: 수기작성 페이지 오류 해결
  src/components/Finance/HandWrite/AssetModal/index.jsx
  src/components/Finance/HandWrite/CategoryModal/index.jsx
  src/pages/Finance/AccountDetail/AccountDetailContent/index.jsx
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/styles/Finance/HandWrite/style.js
Labels: :bug: FIX, :clipboard: CHORE, 🎨 STYLE

#104 fix: 카테고리/자산/만족도 모달 스타일링 수정
  src/components/Finance/AccountDetail/AssetModal/index.jsx
  src/components/Finance/AccountDetail/CategoryModal/index.jsx
  src/components/Finance/AccountDetail/RatingModal/index.jsx
  src/components/Finance/HandWrite/AssetModal/index.jsx
  src/components/Finance/HandWrite/CategoryModal/index.jsx
  src/components/Finance/HandWrite/RatingModal/index.jsx
  src/styles/Finance/HandWrite/RatingModal/style.js
Labels: :bug: FIX, 🎨 STYLE

#106 통계 페이지 Barchart 에 대한 올바른 월별 표시 수정
  src/components/Chart/BarChart/index.jsx
  src/pages/Statistics/StatMain/index.jsx
  src/styles/Statistics/style.js
Labels: :bug: FIX, :recycle: REFACTOR

#108 refactor: 댓글 좋아요 반환 및 답글 수정
  src/api/Comment/commentAPI.js
  src/api/Comment/useCommentAPI.js
  src/api/postAPI.js
  src/api/postListAPI.js
  src/components/Alarm/AlarmCard/index.jsx
  src/components/Community/Board/PostList/index.jsx
  src/components/Community/Post/Comment/CommentList/Comment/index.jsx
  src/components/Community/Post/Comment/CommentList/Reply/index.jsx
  src/components/Community/Post/Comment/CommentList/index.jsx
  src/components/Community/Post/Content/index.jsx
  src/components/Community/Post/MenuBar/CommentMenubar/index.jsx
  src/components/Community/Post/MenuBar/PostMenubar/index.jsx
  src/components/SkeletonUi/AlarmCardSkeleton.jsx
  src/pages/Community/PostDetail/index.jsx
  src/pages/Community/PostWrite/index.jsx
  src/pages/Search/SearchResult/index.jsx
Labels: :recycle: REFACTOR

#105 목표금액설정, 커뮤니티 게시글, 스크랩 취소 api 연결 및 수정
  src/components/User/UserPostCard/index.jsx
  src/pages/User/Setting/Commented/index.jsx
  src/pages/User/Setting/Income/index.jsx
  src/pages/User/Setting/Liked/index.jsx
  src/pages/User/Setting/My/index.jsx
  src/pages/User/Setting/Scrapped/index.jsx
  src/pages/User/UserMain/index.jsx
Labels: :bug: FIX, :sparkles: FEAT

#110 fix: 카메라 기능 수정
  src/components/Finance/Account/DeleteConfirmModal/index.jsx
  src/components/Finance/AccountDetail/OtherSection/index.jsx
  src/components/Finance/Camera/CameraInput/index.jsx
  src/components/Finance/HandWrite/OtherSection/index.jsx
  src/components/common/FloatingButton/FinancePlusButton/index.jsx
  src/pages/Finance/Camera/index.jsx
Labels: :bug: FIX

#112 fix: 카메라 로직 수정 및 수기작성/상세 페이지 input 태그 수정
  src/components/Finance/AccountDetail/OtherSection/index.jsx
  src/components/Finance/Camera/CameraInput/index.jsx
  src/components/Finance/HandWrite/OtherSection/index.jsx
Labels: :bug: FIX

#114 feat: 비밀번호 확인 오류 수정 & 자산 설정 수정
  src/components/User/CateContainer/index.jsx
  src/pages/User/Panel/Password/index.jsx
  src/pages/User/Setting/Liked/index.jsx
Labels: :bug: FIX, :recycle: REFACTOR

#115 feat: 이메일 변경 오류 수정
  src/pages/User/Panel/Email/index.jsx
Labels: :bug: FIX

#116 fix: 카메라 로직 수정 및 수기작성/상세 페이지 input 태그 수정 2
  src/components/Finance/AccountDetail/OtherSection/index.jsx
  src/components/Finance/Camera/CameraInput/index.jsx
  src/components/Finance/HandWrite/OtherSection/index.jsx
Labels: :bug: FIX

#117 Revert "fix: 카메라 로직 수정 및 수기작성/상세 페이지 input 태그 수정 2"
  src/components/Finance/Camera/CameraInput/index.jsx
Labels: :bug: FIX

#120 fix: 카메라 기능 수정
  src/components/Finance/Camera/CameraInput/index.jsx
  src/utils/convertImageToPng.js
Labels: :bug: FIX

#122 fix: 카메라 기능 수정
  src/components/Finance/Camera/CameraInput/index.jsx
Labels: :bug: FIX

#124 refactor: heic2any 라이브러리 설치 및 convertImageToPng코드 수정
  package-lock.json
  package.json
  src/utils/convertImageToPng.js
Labels: :sparkles: FEAT, :recycle: REFACTOR

#129 fix: convertImageToPng코드 수정
  package-lock.json
  package.json
  src/utils/convertImageToPng.js
Labels: :bug: FIX

#130 fix: 코드 정규식 변경
  src/utils/convertImageToPng.js
Labels: :bug: FIX

#131 fix: 오류 메시지 출력하도록 수정
  src/utils/convertImageToPng.js
Labels: :bug: FIX

#133 fix: 사진 파일이 압축되도록 코드 수정
  src/pages/Finance/HandWrite/HandWriteContent/index.jsx
  src/utils/convertImageToPng.js
Labels: :bug: FIX

#119 refactor: 스크랩 버튼 상태 수정
  src/components/Community/Post/Content/index.jsx
  src/pages/Community/PostDetail/index.jsx
  src/styles/Community/SearchProfile/style.js
Labels: :recycle: REFACTOR

#127 feat: 프로필 로딩 문제 해결
  src/components/User/UserProfile/index.jsx
  src/pages/User/Setting/Commented/index.jsx
  src/pages/User/Setting/My/index.jsx
  src/pages/User/Setting/Scrapped/index.jsx
Labels: :bug: FIX
